### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by kcatstack** [swiftype/swiftype-app-search-javascript#56]
When using `swiftype-app-search-javascript` to do search in an app using coffee script, I got `Headers is not defined` error.

**Stack trace**

```
Thu, 28 Feb 2019 03:51:29 GMT - global handler
    ReferenceError: Headers is not defined
    at _request (/opt/<my-app-name>/node_modules/swiftype-app-search-javascript/dist/swiftype_app_search.umd.js:315:23)
    at request (/opt/<my-app-name>/node_modules/swiftype-app-search-javascript/dist/swiftype_app_search.umd.js:303:12)
    at Client._performSearch (/opt/<my-app-name>/node_modules/swiftype-app-search-javascript/dist/swiftype_app_search.umd.js:536:16)
    at Client.search (/opt/<my-app-name>/node_modules/swiftype-app-search-javascript/dist/swiftype_app_search.umd.js:428:21)
    at Object.search (/opt/<my-app-name>/lib/services/swiftype.js:31:21)
```

**Where it crash**
In swiftype_app_search.umd.js at line 315
```
function _request(method, searchKey, apiEndpoint, path, params) {
    var headers = new Headers({
      Authorization: "Bearer " + searchKey,
      "Content-Type": "application/json",
      "X-Swiftype-Client": name,
      "X-Swiftype-Client-Version": version
    });

    return fetch("" + apiEndpoint + path, {
      method: method,
      headers: headers,
      body: JSON.stringify(params),
      credentials: "include"
    });
  }
```

**My usage**
*In coffee script*
```
client.search term, options, (err, content) ->
      if err?
        console.log(JSON.stringify(swiftype_error: err))
        return callback(err)

      ids = content.results.map (res)-> res.doc_id.raw
      return callback(null, ids)
```
*Auto translated to JS*
```
return client.search(term, options, function(err, content) {
      var ids;
      if (err != null) {
          console.log(JSON.stringify({
              swiftype_error: err
          }));
          return callback(err);
      }
      ids = content.results.map(function(res) {
          return res.doc_id.raw;
      });
      return callback(null, ids);
 });
```

**Comment by JasonStoltz** [comment]
@kcatstack What browser are you testing this on? 

`Headers` is a native construct of the Fetch API. https://developer.mozilla.org/en-US/docs/Web/API/Headers

You'll need to Polyfill the Fetch API to get this working: https://github.com/swiftype/swiftype-app-search-javascript#browser-support.

I think long term we might consider changing the client to use something other than the Fetch API for making network requests.

**Comment by kcatstack** [comment]
Thank @JasonStoltz for responding. It's my bad actually. I used it for a node backend service. Should have used `swiftype-app-search-node`.

However, there is a workaround for this if anyone is really looking for it:

```
const fetch = require('node-fetch');
global.fetch = fetch
global.Headers = fetch.Headers;
```
